# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvQMIaagUsJpSr8iSoyvkM87BQsrDday

# Nabila Luthfia Arifin - 1301204077
# Nabiel Muhammad Al-Ghazali - 1301204497
"""

!pip install bokeh

import pandas as pd
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_file
from bokeh.models import ColumnDataSource, HoverTool, CustomJS, Select
from bokeh.layouts import row, column
from bokeh.io import output_notebook
output_notebook()

from google.colab import drive
drive.mount('/content/drive')

df_covid19 = pd.read_csv("/content/drive/MyDrive/Indonesia-Covid19.csv",encoding='ISO-8859-1') 
df_covid19.shape

df_covid19

columns =df_covid19.columns
columns
names =[ x for x in columns]
print (names)

df_covid19.rename(columns={'ï»¿Date' : 'Date'},inplace=True)

df_covid19

#info data
df_covid19.info()

# missing value
df_covid19.isnull().any()

# menghapus missing value
df_covid19.dropna(inplace=True)

df_covid19.isnull().sum()

#drop data dikarenakan terdapat beberapa atribut yang tidak terlalu dibutuhkan nilainya
df_covid19.drop('Longitude', inplace=True, axis=1)
df_covid19.drop('Latitude', inplace=True, axis=1)
df_covid19.drop('New Cases per Million', inplace=True, axis=1)
df_covid19.drop('Total Cases per Million', inplace=True, axis=1)
df_covid19.drop('New Deaths per Million', inplace=True, axis=1)
df_covid19.drop('Total Deaths per Million', inplace=True, axis=1)
df_covid19.drop('Total Deaths per 100rb', inplace=True, axis=1)

# melihat provinsi yang terpapar covid 19
province = df_covid19['Location'].unique()
province

# Merubah format tipe data dalam kolom tanggal
df_covid19['Date'] = pd.to_datetime(df_covid19['Date'])
df_covid19.dtypes

# Buat variabel untuk Provinsi Jawa Barat
df_covid19_Jabar = pd.DataFrame(df_covid19[df_covid19["Location"] == 'Jawa Barat'])
df_covid19_Jabar.head()

# Buat variabel untuk Provinsi Jawa Tengah
df_covid19_Jateng = pd.DataFrame(df_covid19[df_covid19["Location"] == 'Jawa Tengah'])
df_covid19_Jateng.head()

# Buat variabel untuk Provinsi Sumatera Utara
df_covid19_Sumut = pd.DataFrame(df_covid19[df_covid19["Location"] == 'Sumatera Utara'])
df_covid19_Sumut.head()

# Buat variabel untuk Provinsi Banten
df_covid19_Banten = pd.DataFrame(df_covid19[df_covid19["Location"] == 'Banten'])
df_covid19_Banten.head()

# Buat variabel untuk Provinsi Bali
df_covid19_Bali = pd.DataFrame(df_covid19[df_covid19["Location"] == 'Bali'])
df_covid19_Bali.head()

# Simpan data pada ColumnDataSource
source_Jabar = ColumnDataSource(df_covid19_Jabar)
source_Jateng = ColumnDataSource(df_covid19_Jateng)
source_Sumut = ColumnDataSource(df_covid19_Sumut)
source_Banten = ColumnDataSource(df_covid19_Banten)
source_Bali = ColumnDataSource(df_covid19_Bali)

# Membuat file output dalam format html
output_file('Hasil Analisis Data Covid-19 di Indonesia.html', title='Data Covid')

# Buat tooltips dan hover

tooltips = [('Location','@Location'), ('Growth Factor of New Cases', '@Growth Factor of New Cases')]
tooltips1 = [('Location','@Location'), ('Growth Factor of New Cases', '@Growth Factor of New Cases')]
tooltips2 = [('Location','@Location'), ('Total Cases','@Total Cases')]
tooltips3 = [('Location','@Location'), ('New Cases', '@New Cases')]

# Buat Figure Analisis
fig = figure(plot_height=600, plot_width=800, x_axis_type='datetime', x_axis_label='Date', y_axis_label='Growth Factor of New Cases',
             title='Pertumbuhan Kasus Baru Covid 5 Provinsi Terpadat di Indonesia')

fig.add_tools(HoverTool(tooltips=tooltips))

fig.line(x='Date', y='Growth Factor of New Cases', source=source_Jabar, legend_label='Jawa Barat', color='red')
fig.line(x='Date', y='Growth Factor of New Cases', source=source_Jateng, legend_label='Jawa Tengah', color='blue')
fig.line(x='Date', y='Growth Factor of New Cases', source=source_Sumut, legend_label='Sumatera Utara', color='yellow')
fig.line(x='Date', y='Growth Factor of New Cases', source=source_Banten, legend_label='Banten', color='green')
fig.line(x='Date', y='Growth Factor of New Cases', source=source_Bali, legend_label='Bali', color='black')

options = [tooltips, tooltips1, tooltips2, tooltips3]

# Buat callback untuk mengupdate tooltips
callback = CustomJS (args=dict(tt=fig.hover, opts=options), code="""
    if (cb_obj.value=='Normal') {
        tt[0].tooltips=opts[0]
    } else if (cb_obj.value=='Growth Factor of New Cases') {
      tt[0].tooltips=opts[1]
    } else if (cb_obj.value=='Total Cases') {
      tt[0].tooltips=opts[2]
    } else {
        tt[0].tooltips=opts[3]
    }
    """)

# Buat menu dropdown parameter
stat_select = Select(options=['Total Cases', 'New Cases', 'Growth Factor of New Cases'], title='Parameter:')
stat_select.js_on_change("value", callback)

"""# Visualisasi Data"""

fig.legend.location = "top_right"
fig.legend.click_policy="hide"
show(column(stat_select,fig))